import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="w-100">
          <nav className="flex w-100">
            <Link href="/">Home</Link>
            <Link href="/management">Management Library</Link>
          </nav>
        </header>
        {children}
        <footer></footer>
        </body>
    </html>
  );
}
